### ISSUE TITLE
Testimonial box - quote 'too large'

### ISSUE THREAD

**Issue by Jbarget** [fatlama/issues#1]
hey gang!
just noticed that the user's picture is not shown because of the size of the quote

![screen shot 2016-11-24 at 11 23 29](https://cloud.githubusercontent.com/assets/11725595/20596869/84e2eab2-b238-11e6-8f5e-e8c154ba501a.png)

**Comment by otajor** [comment]
Thanks for flagging this Justen :) fixed now!
