### ISSUE TITLE
Cancelling within sign-up/sign-in modal

### ISSUE THREAD

**Issue by jackcarlisle** [fatlama/issues#2]
If I'm on the home page and then navigate to one of the six options underneath 'What can I use it for' and then click `Cancel` on the modal: 

![screen shot 2016-11-24 at 12 43 35](https://cloud.githubusercontent.com/assets/12450298/20599045/0393941e-b244-11e6-85f5-f958b4dace86.png)

The thumbnails for the example listings disappear after being redirected to the homepage: 
<img width="1672" alt="screen shot 2016-11-24 at 12 43 06" src="https://cloud.githubusercontent.com/assets/12450298/20599056/16de4334-b244-11e6-8242-15cac9e3722b.png">

**Comment by jackcarlisle** [comment]
Ps. it's looking so slick!

**Comment by otajor** [comment]
Fixed :) Thanks for reporting it.
